name: Build wheels in a container

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: "The runner to use for the build"
        required: true
        type: string
        default: ubuntu-22.04
      container-image:
        description: "Container image"
        required: true
        type: string
      upload-to-release:
        description: "Upload wheel to this release"
        required: false
        type: boolean
        default: false
      release-version:
        description: "Upload wheel to this release"
        required: false
        type: string

  push:

jobs:
  build-wheels:
    uses: ./.github/workflows/_build_in_container.yml
    with:
      runs-on: ${{ inputs.runs-on || 'ubuntu-22.04' }}
      container-image: ${{ inputs.container-image || 'nvcr.io/nvidia/pytorch:25.06-py3' }}
      upload-to-release: ${{ inputs.upload-to-release || false }}
      release-version: ${{ inputs.release-version || 'v2.2.5' }}
